trigger:
- main

# Use self-hosted agent from Default pool
pool:
  name: Default

variables:
  appName: demowebapp878
  artifactName: drop
  azureServiceConnection: Azure-SP-Connection   # <-- CHANGE if different

stages:

# =========================
# STAGE 1: BUILD
# =========================
- stage: Build
  displayName: Build Application
  jobs:
  - job: BuildJob
    displayName: Build & Publish Artifact
    steps:
    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: '8.x'

    - task: DotNetCoreCLI@2
      inputs:
        command: restore
        projects: '**/*.csproj'

    - task: DotNetCoreCLI@2
      inputs:
        command: publish
        projects: '**/*.csproj'
        arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory)'
        zipAfterPublish: true

    - publish: $(Build.ArtifactStagingDirectory)
      artifact: $(artifactName)

# =========================
# STAGE 2: CANARY DEPLOY
# =========================
- stage: Deploy_Canary
  displayName: Deploy to Canary Slot
  dependsOn: Build
  jobs:
  - deployment: CanaryDeploy
    displayName: Deploy to Canary
    environment: canary
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: $(artifactName)

          - task: AzureWebApp@1
            displayName: Deploy to Canary Slot
            inputs:
              azureSubscription: $(azureServiceConnection)
              appName: $(appName)
              slotName: canary
              package: $(Pipeline.Workspace)/$(artifactName)/**/*.zip

# =========================
# STAGE 3: VALIDATION
# =========================
- stage: Validate
  displayName: Canary Validation
  dependsOn: Deploy_Canary
  jobs:
  - job: CanaryHealth
    displayName: Health Check
    steps:
    - script: |
        echo "Running health check..."
        curl https:/ YOUR-CANARY-URL
      displayName: Canary Health Check

# =========================
# STAGE 4: PROMOTE TO PROD
# =========================
- stage: Promote
  displayName: Promote Canary to Production
  dependsOn: Validate
  jobs:
  - deployment: SwapSlots
    displayName: Swap Slots
    environment: production
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureAppServiceManage@0
            displayName: Swap Canary with Production
            inputs:
              azureSubscription: $(azureServiceConnection)
              action: Swap Slots
              WebAppName: 'your-app-name'
              ResourceGroupName: your-resource-group-name
              sourceSlot: canary
              targetSlot: production

