trigger:
- main

pool:
  name: myagent

variables:
  appName: demowebapp878
  artifactName: drop

stages:
- stage: Build
  jobs:
  - job: BuildJob
    pool:
      vmImage: windows-latest
    steps:
    - task: DotNetCoreCLI@2
      inputs:
        command: publish
        projects: '**/*.csproj'
        arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory)'
        zipAfterPublish: true
    - publish: $(Build.ArtifactStagingDirectory)
      artifact: $(artifactName)

- stage: Deploy_Canary
  dependsOn: Build
  jobs:
  - deployment: CanaryDeploy
    environment: canary
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: $(artifactName)
          - task: AzureWebApp@1
            inputs:
              appName: $(appName)
              slotName: canary
              package: $(Pipeline.Workspace)/$(artifactName)/**/*.zip

- stage: Validate
  dependsOn: Deploy_Canary
  jobs:
  - job: CanaryHealth
    steps:
    - script: |
        curl https://demowebapp878-canary.azurewebsites.net/health
      displayName: Health Check

- stage: Promote
  dependsOn: Validate
  jobs:
  - deployment: SwapSlots
    environment: production
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureAppServiceManage@0
            inputs:
              action: Swap Slots
              appName: $(appName)
              sourceSlot: canary
              targetSlot: production
